# imagem base do Python
FROM python:3.9

# Define o diretório de trabalho no contêiner
WORKDIR /app

# Copia os arquivos necessários para o contêiner
COPY genetic_algorithm.py /app/genetic_algorithm.py

# Instala as dependências
RUN pip install numpy

# Comando padrão a ser executado quando o contêiner for iniciado
CMD ["python", "/app/genetic_algorithm.py"]
